In [215]:
import pandas as pd
import numpy as np
import math
from sklearn.linear_model import LinearRegression

In [194]:
math.log(math.exp(1))

1.0

In [208]:
def softplus (x):
    return math.log(1+math.exp(x))
def x_and_plus (i,x,p):
    return i * x + p

In [214]:
for i in range(0,101,25):
    k=i/100
    print (f"{k}\t{round(x_and_plus(softplus(x_and_plus(k,-2.52,1.29)),2.28,0),2)}")

0.0	3.5
0.25	2.45
0.5	1.61
0.75	1.0
1.0	0.58


In [221]:
X = np.array([0,1,2,2.5]).reshape((-1,1))
y = np.array([1,1.9,3.2,3.4])
reg = LinearRegression()
reg.fit(X,y)
reg.coef_, reg.intercept_

# X,y

(array([1.01355932]), 0.9813559322033898)

In [224]:
X = np.array([[4,2],[6,2],[2,4],[4,4],[4,6],[6,4]])
y = ['d','b','d','b','d','d']
X,y


(array([[4, 2],
        [6, 2],
        [2, 4],
        [4, 4],
        [4, 6],
        [6, 4]]),
 ['d', 'b', 'd', 'b', 'd', 'd'])

In [227]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=3)
model.fit(X,y)
model.predict([[8,2]])

array(['d'], dtype='<U1')

In [228]:
# import matplotlib.pyplot as plt
# from kneed import KneeLocator
# from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
# from sklearn.metrics import silhouette_score
from sklearn.preprocessing import StandardScaler

In [231]:
features = np.array([[0,0],[5,0],[10,0],[0,7],[5,7],[10,7]])
init = np.array([[0,7],[5,7],[10,7]])

model = KMeans(init=init,n_clusters=3)
model.fit(features)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:1146: RuntimeWarning: Explicit initial center position passed: performing only one init in KMeans instead of n_init=10.
  self._check_params(X)


KMeans(init=array([[ 0,  7],
       [ 5,  7],
       [10,  7]]), n_clusters=3)

In [234]:
features, model.labels_

(array([[ 0,  0],
        [ 5,  0],
        [10,  0],
        [ 0,  7],
        [ 5,  7],
        [10,  7]]),
 array([0, 1, 2, 0, 1, 2], dtype=int32))

In [236]:
from sklearn.metrics.pairwise import cosine_similarity
X = np.array([[3,2,0,5,0,0,0,2,0,0]])
y = np.array([[1,0,0,0,0,0,0,1,0,2]])
cosine_similarity(X , y)

array([[0.31497039]])

In [241]:
5/math.sqrt(6*42), 12/math.sqrt(6*42)

(0.314970394174356, 0.7559289460184544)

In [245]:
X = np.array(['L','F','L','T','M','F','M','T','H','F','H','T']).reshape(-1,2)
y = np.array(['F','T','F','T','T','T'])
X,y

(array([['L', 'F'],
        ['L', 'T'],
        ['M', 'F'],
        ['M', 'T'],
        ['H', 'F'],
        ['H', 'T']], dtype='<U1'),
 array(['F', 'T', 'F', 'T', 'T', 'T'], dtype='<U1'))

In [246]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X,y)
model.predict(['L','T'])

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/utils/validation.py:964: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  X = check_array(


ValueError: Unable to convert array of bytes/strings into decimal numbers with dtype='numeric'